name: harmony-api
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Remove __test__ for build
        run: rm -rf __test__
      - name: Install dependencies
        run: npm ci --omit=dev
      - name: Generate Prisma Client
        run: npx prisma generate --schema ./prisma/schema.prisma
      - name: Build project
        run: tsc

  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Run local DB for testing, tests and linter
        run: |
          export POSTGRES_USER=username
          export POSTGRES_PASSWORD=password
          export POSTGRES_PORT=5432
          export POSTGRES_DB_NAME=postgres_db
          export POSTGRES_DB=postgres_db
          export POSTGRES_DB_HOST=localhost
          export POSTGRES_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_DB_HOST:$POSTGRES_PORT/$POSTGRES_DB_NAME

          cd ../harmony-db
          docker-compose up -d

          cd ../harmony-api

          npx prisma migrate dev
          npm run test
