name: harmony-api
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: tsc
  
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Run DB for testing
        env:
          PORT: 8081
          POSTGRES_USER: ${{ secrets.POSTGRES_USER_CI }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_CI }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT_CI }}
          POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME_CI }}
          POSTGRES_DB_HOST: localhost
          POSTGRES_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}"
        run: |
          echo "--------------"
          printenv
          echo "--------------"
          
          cd ../harmony-db
          docker-compose up -d
      - name: Run tests and linter
        env:
          PORT: 8081
          POSTGRES_USER_CI: ${{ secrets.POSTGRES_USER_CI }}
          POSTGRES_PASSWORD_CI: ${{ secrets.POSTGRES_PASSWORD_CI }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT_CI }}
          POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME_CI }}
          POSTGRES_DB_HOST: localhost
          POSTGRES_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}"
        run: |
          echo "--------------"
          printenv
          echo "--------------"
          
          npm run test
