name: harmony-api
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Remove __test__ for build
        run: rm -rf __test__
      - name: Install dependencies
        run: npm ci --omit=dev
      - name: Generate Prisma Client
        run: npx prisma generate --schema ./prisma/schema.prisma
      - name: Build project
        run: tsc

  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate --schema ./prisma/schema.prisma
      - name: Run unit tests
        run: npm run unit-tests

  integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Generate and connect to Prisma client
        run: npm run connectprisma

      - name: Run integration tests on remote DB
        run: |
          export PORT=8081
          export POSTGRES_USER=${{ secrets.POSTGRES_USER_CI }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_CI }}
          export POSTGRES_PORT=${{ secrets.POSTGRES_PORT_CI }}
          export POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME_CI }}
          export DB_HOST=${{ secrets.azureHost2 }}
          export POSTGRES_URL=postgresql://${{ secrets.POSTGRES_USER_CI }}:${{ secrets.POSTGRES_PASSWORD_CI }}@${{ secrets.azureHost2 }}:${{ secrets.POSTGRES_PORT_CI }}/${{ secrets.POSTGRES_DB_NAME_CI }}

          # Testing DB connection (URL, whether it is correct)
          psql $POSTGRES_URL

          cd ../harmony-api

          npm run integration-tests

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate --schema ./prisma/schema.prisma
      - name: Run linter
        run: npm run lint
