name: harmony-api
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: tsc
  
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Run DB for testing
        run: |
          sudo echo "
            # Port that this server will be accessible on
            PORT=8081

            # Name of the user we will access with (for Prisma DB URL)
            POSTGRES_USER=${{ secrets.POSTGRES_USER_CI }}

            # Password of the user (for Prisma DB URL)
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_CI }}

            # Port that Prisma will access the DB From
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT_CI }}

            # Name of the database
            POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME_CI }}

            # DB Host or IP
            DB_HOST=localhost

            #Database URL for Prisma to get the DB from (Created off the previous entries)
            POSTGRES_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}"
          " | sudo tee -a .env

          cp .env ../harmony-db
          
          cd ../harmony-db
          docker-compose up -d
      - name: Run tests and linter
        run: npm run test
