name: api-ci-integration
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: tsc
  
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./harmony-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
        
      - name: Run integration tests on remote DB and linter 
        run: |
          export PORT=8081
          export POSTGRES_USER=${{ secrets.POSTGRES_USER_CI }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_CI }}
          export POSTGRES_PORT=${{ secrets.POSTGRES_PORT_CI }}
          export POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME_CI }}
          export DB_HOST=${{ secrets.azureHost2 }}
          export POSTGRES_URL=postgresql://${{ secrets.POSTGRES_USER_CI }}:${{ secrets.POSTGRES_PASSWORD_CI }}@${{ secrets.azureHost2 }}:${{ secrets.POSTGRES_PORT_CI }}/${{ secrets.POSTGRES_DB_NAME_CI }}

          # Testing DB connection (URL, whether it is correct)
          psql $POSTGRES_URL
          
          cd ../harmony-api
        
          npx prisma migrate dev
          npm run test