name: bulding-docker-fe

on:
  push

jobs:
  build_docker_fe:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.usernameDocker }}
          password: ${{ secrets.apiKeyDocker }}

      - name: Harmony FE - Create and set .env.prod with correct secrets
        run: |
          cd ./harmony-fe
          touch ./environment/.env.prod
          echo "NEXT_PUBLIC_API_BASE_ENDPOINT=https://harmonysocial.ca:8081" >> ./environment/.env.prod

      - name: Harmony FE - Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: aprovozin/harmony-fe-cd
      
      - name:  Harmony FE - Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./harmony-fe
          file: ./harmony-fe/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ENV=prod